[theme]
base = "dark"
primaryColor = "#7c83ff"
backgroundColor = "#0d0e12"
secondaryBackgroundColor = "#15171f"
textColor = "#e7e8ec"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
runOnSave = false
